"""empty message

Revision ID: 8f722fee6c67
Revises: c281a22d3535
Create Date: 2019-07-25 12:46:39.695309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f722fee6c67'
down_revision = 'c281a22d3535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('ends', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('location', sa.String(), nullable=True))
    op.add_column('resource', sa.Column('starts', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'starts')
    op.drop_column('resource', 'location')
    op.drop_column('resource', 'ends')
    # ### end Alembic commands ###
