"""empty message

Revision ID: c281a22d3535
Revises: 4cc603fb7056
Create Date: 2019-07-24 17:42:40.145720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'c281a22d3535'
down_revision = '4cc603fb7056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    segment = op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('resource', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource', 'segment', ['segment_id'], ['id'])
    # ### end Alembic commands ###

    data = [
        {'id':1, 'name':'Resource'},
        {'id':2, 'name':'Event'}
    ]
    op.bulk_insert(segment, data)

    resource = table('resource',
        column('segment_id', sa.Integer())
    )
    op.execute(
        resource.update().
        values({"segment_id": 1})
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'segment_id')
    op.drop_table('segment')
    # ### end Alembic commands ###
 
    resource = table('resource',
        column('segment_id', sa.Integer())
    )
    op.execute(
        resource.update().
        values({"segment_id": None})
    )

